### ISSUE TITLE
Transporter timeout & heartbeat from config file

### ISSUE THREAD

**Issue by lisek-eth** [block-api/block-node#4]
Right now default timeout for actions and heartbeat interval are hardcoded - these should be available to set through config file in `transporter` section

```yml
transporter:
  timeout: 30 # default timeout for actions, in seconds
  heartbeatInterval: 5 # in seconds
```
